# Site settings
title: Personal website of Urszula Czerwinska, Deep Learning Engineer,  Data Scientist
description: Blog and personal journey to Data Science, Machine Learning, Deep Learning, Artificial Intelligence | How to become a Data Scientist | How to become a Machine Learning Engineer | My journey from PhD to Data Scientist
tagline: A blog about Data Science, Machine Learning, Deep Learning, Artificial Intelligence
owner:
  name: Urszula Czerwinska # or company name
  email: urszula.czerwinska@cri-paris.com
  url: http://urszulaczerwinska.github.io
first_published: 2016
baseurl: ""
url: "http://urszulaczerwinska.github.io" # the base hostname & protocol for your site

# on landing page
# - set the greeting only if you want to display the first green section
greeting:
  title: Welcome
  text: to the world of Data & Science
# - title for your blog's featured posts
features-title: Recent posts
# - displayed at the bottom
closing-head: Thanks for visiting
closing-para: Feel free to get in touch!

# on all pages (and the first three you list display with greeting, if included)
social:
  twitter: https://twitter.com/ulalaparis
  github: https://github.com/urszulaczerwinska
  linkedin-square: https://linkedin.com/in/urszulaczerwinska
  email: mailto:ulcia.liberte@gmail.com

compose:
  editor: subl
  extension: md


navlinks: bottom

# expecting more works? mark your list as in-progress
works_in_progress: yes

# If you have custom extensions, specifically includes/_my/custom.scss,
# set this to yes
custom_extensions: no

# Build settings
permalink: /:categories/:title.html
markdown: kramdown
#sass:
#  style: compressed
exclude: ['site.bat','compose.rb','README.md']
include: ['_pages','.htaccess']
defaults:
  - scope:
      path: _pages
    values:
      layout: page
      #permalink: /:slug/ # dunna work. See github.com/jekyll/jekyll/issues/2280
  - scope:
      path: _posts
    values:
      layout: post
  - scope:
      path: _drafts
    values:
      layout: post

plugins:
  - jekyll-seo-tag
# to initialize arrays in assignments (assign myarr = site.empty_array)
# (easier to grok than assign myarr = '' | split',')
empty_array: []

