# Site settings
title: Urszula Czerwinska | Python, TensorFlow Expert | Data Scientist & Deep Learning Engineer
description: Explore the journey of Urszula Czerwinska from PhD to Data Science, featuring insights on Data Science projects, Machine Learning, and Deep Learning. Discover how to become a Data Scientist or Machine Learning Engineer.
tagline: A blog about Data Science, Machine Learning, Deep Learning, Artificial Intelligence
owner:
  name: Urszula Czerwinska # or company name
  email: urszula.czerwinska@cri-paris.com
  url: http://urszulaczerwinska.github.io
first_published: 2016
baseurl: ""
url: "http://urszulaczerwinska.github.io" # the base hostname & protocol for your site

# on landing page
# - set the greeting only if you want to display the first green section
greeting:
  title: Welcome to My Data Science Journey
  text: Welcome to my personal blog, where I documented my transition from a PhD in Computational Biology to a thriving career in Data Science. Here, you'll find insights on where to learn data science, how data science and machine learning, artificial intelligence are revolutionizing various fields, and explore whether data science can be self-taught, are data science bootcamps or courses worth it. Discover why data science is important in today's world.
# - title for your blog's featured posts
features-title: Recent posts
# - displayed at the bottom
closing-head: Thanks for visiting, dear Data Science Lover !
closing-para: Feel free to get in touch and talk about how deep learning can help your business or solve your problem. Let's connect!
# on all pages (and the first three you list display with greeting, if included)
social:
  twitter: https://twitter.com/ulalaparis
  github: https://github.com/urszulaczerwinska
  linkedin-square: https://linkedin.com/in/urszulaczerwinska
  email: mailto:ulcia.liberte@gmail.com

compose:
  editor: subl
  extension: md


navlinks: bottom

# expecting more works? mark your list as in-progress
# works_in_progress: no

# If you have custom extensions, specifically includes/_my/custom.scss,
# set this to yes
custom_extensions: false

# Build settings
permalink: /:categories/:title.html
markdown: kramdown
#sass:
#  style: compressed

exclude: ['site.bat','compose.rb','README.md']
include: ['_pages','.htaccess']
defaults:
  - scope:
      path: _pages
    values:
      layout: page
      seo_description_max_words: 200
      image:
        path: images/engineering.jpg
        alt: Urszula Czerwinska | Data Scientist & Deep Learning Engineer | Data Science Projects | Machine Learning | Deep Learning | Artificial Intelligence | Deep Learning Algorithms in industry
  - scope:
      path: _posts
    values:
      layout: post
      seo_description_max_words: 200
      image:
        path: images/writing.jpeg
        alt: Stories / blog about Data Science, Machine Learning, Deep Learning, Artificial Intelligence, transition from PhD to Data Science | from academia to industry
  - scope:
      path: _drafts
    values:
      layout: post
      seo_description_max_words: 200


plugins:
  - jekyll-seo-tag
# to initialize arrays in assignments (assign myarr = site.empty_array)
# (easier to grok than assign myarr = '' | split',')
empty_array: []

author:
  name: "Urszula Czerwinska"
  description: "Data Scientist & Deep Learning Engineer"
  url: "https://www.linkedin.com/in/urszula-czerwinska/"
